FROM scratch AS asteroid_core

COPY images/asteroid/files /

# Base Image
FROM  ghcr.io/huntedraven7/blueprint:arch

# Copy asteroid_core
COPY images/asteroid/files/system_files /

# Brew
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/00-config.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/10-files.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/packages/00-bootstrap.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/packages/10-repos.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/kernel/install.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/temporary-users.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/packages/20-packages.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/packages/30-desktop.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/setup/20-services.sh

# Finalize
RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/final/build-initramfs.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/final/workarounds.sh

RUN --mount=type=bind,from=asteroid_core,source=/,target=/asteroid_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asteroid_core/scripts/final/clean-up.sh


RUN bootc container lint
