FROM scratch AS asterazzite_core

COPY build_files/system /
COPY images/asterazzite/files /

# Base Image
FROM ghcr.io/ublue-os/bazzite-nvidia-open:stable

# Copy asterazzite_core
COPY images/asterazzite/files/system_files /

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/setup/10-files.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/setup/packages/00-repos.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/setup/packages/20-packages.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/setup/packages/30-desktop.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/setup/20-services.sh

# Finalize
RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/final/build-initramfs.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/final/workarounds.sh

RUN --mount=type=bind,from=asterazzite_core,source=/,target=/asterazzite_core \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /asterazzite_core/scripts/final/clean-up.sh


RUN bootc container lint
